import type { CityTerrainId } from './terrain'

/** 大戦略 FC 風の限定パレット */
export const PIXEL_COLORS: Record<string, string> = {
  '.': 'transparent',
  K: '#101010',
  B: '#2858b8',
  b: '#183878',
  G: '#808080',
  g: '#b0b0b0',
  D: '#585858',
  W: '#e8e8e8',
  w: '#c8c8c8',
  R: '#a06830',
  r: '#c08040',
  S: '#989898',
  s: '#c0c0c0',
}

export const HEX_PATH = 'M 12 1 L 22 6.5 L 22 15.5 L 12 21 L 2 15.5 L 2 6.5 Z'

const FACTORY_MAP = [
  '........................',
  '........................',
  '....DD......gggg........',
  '....DD......gGGg........',
  '....DD......gGGg........',
  '....DD......gGGg........',
  '....DD..ggggGGGG........',
  '....DD..gGGGGGGG........',
  '....DD..gGGGGGGG........',
  '....DD..ggggGGGG........',
  '.........gGGGGg.........',
  '.........gggggg.........',
  '........................',
  '.....rrrrrrrrrrrrr......',
  '.....RRRRRRRRRRRRR......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
]

const AIRFIELD_MAP = [
  '........................',
  '........................',
  '........................',
  '..........ss............',
  '.........sSSs...........',
  '........sSSSs...........',
  '.......sSSSSs...........',
  '......sSSSSSs...........',
  '.....sSSSSSSs...........',
  '....sSSSSSSSs...........',
  '...sSSSSSSSSs...........',
  '..sSSSSSSSSSs...........',
  '.sSSSSSSSSSSs...........',
  'sSSSSSSSSSSSSs..........',
  '.sSSSSSSSSSSs...........',
  '..sSSSSSSSSSs...........',
  '...sSSSSSSSSs...........',
  '....sSSSSSSs............',
  '.....sSSSSs.............',
  '......sSSs..............',
  '.......sss..............',
  '........................',
]

const CAPITAL_MAP = [
  '........................',
  '..........WW............',
  '.........WWWW...........',
  '........WWWWWW..........',
  '.......WWWWWWWW.........',
  '......WWWWWWWWWW........',
  '.....WWWWWWWWWWWW.......',
  '....WWWWWWWWWWWWWW......',
  '...WWWWWWWWWWWWWWWW.....',
  '..WWWWWWWWWWWWWWWWWW....',
  '.WWwWWWWWWWWWWWWwWWWW...',
  '..WWwWWWWWWWWWWwWWWW....',
  '...WWwWWWWWWWWwWWWW.....',
  '....WWwWWWWWWwWWWW......',
  '.....WWwWWWWwWWWW.......',
  '......WWwWWwWWWW........',
  '.......WWWWWW...........',
  '........WWWW............',
  '.....rrrrrrrrrrrrr......',
  '.....RRRRRRRRRRRRR......',
  '........................',
  '........................',
]

const CITY_MAP = [
  '........................',
  '........................',
  '....gg....ggg...gg......',
  '....GG....GGG...GG......',
  '....GG....GGG...GG......',
  '....GG....GGG...GGg.....',
  '....GGg...GGG...GGG.....',
  '....GGG...GGG...GGG.....',
  '....GGG...GGG...GGG.....',
  '....GGG...GGG...GGG.....',
  '....GGG...GGG...GGG.....',
  '....ggg...ggg...ggg.....',
  '........................',
  '.....rrrrrrrrrrrrr......',
  '.....RRRRRRRRRRRRR......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
]

export const TERRAIN_MAPS: Record<CityTerrainId, string[]> = {
  factory: FACTORY_MAP,
  airfield: AIRFIELD_MAP,
  capital: CAPITAL_MAP,
  city: CITY_MAP,
}
